//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostConnectivityStatus) DeepCopyInto(out *HostConnectivityStatus) {
	*out = *in
	if in.LastHandshakeTime != nil {
		in, out := &in.LastHandshakeTime, &out.LastHandshakeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostConnectivityStatus.
func (in *HostConnectivityStatus) DeepCopy() *HostConnectivityStatus {
	if in == nil {
		return nil
	}
	out := new(HostConnectivityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomHost) DeepCopyInto(out *IdleloomHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomHost.
func (in *IdleloomHost) DeepCopy() *IdleloomHost {
	if in == nil {
		return nil
	}
	out := new(IdleloomHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomHostList) DeepCopyInto(out *IdleloomHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdleloomHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomHostList.
func (in *IdleloomHostList) DeepCopy() *IdleloomHostList {
	if in == nil {
		return nil
	}
	out := new(IdleloomHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomHostSpec) DeepCopyInto(out *IdleloomHostSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomHostSpec.
func (in *IdleloomHostSpec) DeepCopy() *IdleloomHostSpec {
	if in == nil {
		return nil
	}
	out := new(IdleloomHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomHostStatus) DeepCopyInto(out *IdleloomHostStatus) {
	*out = *in
	if in.RuntimeProfiles != nil {
		in, out := &in.RuntimeProfiles, &out.RuntimeProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ModelFamilies != nil {
		in, out := &in.ModelFamilies, &out.ModelFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AllocatableUnifiedMemory = in.AllocatableUnifiedMemory.DeepCopy()
	out.AvailableUnifiedMemory = in.AvailableUnifiedMemory.DeepCopy()
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = new(HostConnectivityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomHostStatus.
func (in *IdleloomHostStatus) DeepCopy() *IdleloomHostStatus {
	if in == nil {
		return nil
	}
	out := new(IdleloomHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomModel) DeepCopyInto(out *IdleloomModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomModel.
func (in *IdleloomModel) DeepCopy() *IdleloomModel {
	if in == nil {
		return nil
	}
	out := new(IdleloomModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomModelList) DeepCopyInto(out *IdleloomModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdleloomModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomModelList.
func (in *IdleloomModelList) DeepCopy() *IdleloomModelList {
	if in == nil {
		return nil
	}
	out := new(IdleloomModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomModelSpec) DeepCopyInto(out *IdleloomModelSpec) {
	*out = *in
	out.Artifact = in.Artifact
	out.MinimumUnifiedMemory = in.MinimumUnifiedMemory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomModelSpec.
func (in *IdleloomModelSpec) DeepCopy() *IdleloomModelSpec {
	if in == nil {
		return nil
	}
	out := new(IdleloomModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomModelStatus) DeepCopyInto(out *IdleloomModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomModelStatus.
func (in *IdleloomModelStatus) DeepCopy() *IdleloomModelStatus {
	if in == nil {
		return nil
	}
	out := new(IdleloomModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkload) DeepCopyInto(out *IdleloomWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkload.
func (in *IdleloomWorkload) DeepCopy() *IdleloomWorkload {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadAssignment) DeepCopyInto(out *IdleloomWorkloadAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadAssignment.
func (in *IdleloomWorkloadAssignment) DeepCopy() *IdleloomWorkloadAssignment {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomWorkloadAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadAssignmentList) DeepCopyInto(out *IdleloomWorkloadAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdleloomWorkloadAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadAssignmentList.
func (in *IdleloomWorkloadAssignmentList) DeepCopy() *IdleloomWorkloadAssignmentList {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomWorkloadAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadAssignmentSpec) DeepCopyInto(out *IdleloomWorkloadAssignmentSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	out.HostRef = in.HostRef
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ResolvedModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = new(ResolvedShell)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadAssignmentSpec.
func (in *IdleloomWorkloadAssignmentSpec) DeepCopy() *IdleloomWorkloadAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadAssignmentStatus) DeepCopyInto(out *IdleloomWorkloadAssignmentStatus) {
	*out = *in
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.StopAcknowledgement != nil {
		in, out := &in.StopAcknowledgement, &out.StopAcknowledgement
		*out = new(StopAcknowledgement)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadAssignmentStatus.
func (in *IdleloomWorkloadAssignmentStatus) DeepCopy() *IdleloomWorkloadAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadList) DeepCopyInto(out *IdleloomWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdleloomWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadList.
func (in *IdleloomWorkloadList) DeepCopy() *IdleloomWorkloadList {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdleloomWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadSpec) DeepCopyInto(out *IdleloomWorkloadSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(WorkloadModelReference)
		**out = **in
	}
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = new(WorkloadShell)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadSpec.
func (in *IdleloomWorkloadSpec) DeepCopy() *IdleloomWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleloomWorkloadStatus) DeepCopyInto(out *IdleloomWorkloadStatus) {
	*out = *in
	if in.SchedulingIntent != nil {
		in, out := &in.SchedulingIntent, &out.SchedulingIntent
		*out = new(WorkloadSchedulingIntent)
		(*in).DeepCopyInto(*out)
	}
	if in.AssignmentRef != nil {
		in, out := &in.AssignmentRef, &out.AssignmentRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleloomWorkloadStatus.
func (in *IdleloomWorkloadStatus) DeepCopy() *IdleloomWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(IdleloomWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelArtifact) DeepCopyInto(out *ModelArtifact) {
	*out = *in
	out.Signature = in.Signature
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelArtifact.
func (in *ModelArtifact) DeepCopy() *ModelArtifact {
	if in == nil {
		return nil
	}
	out := new(ModelArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedModel) DeepCopyInto(out *ResolvedModel) {
	*out = *in
	out.CatalogRef = in.CatalogRef
	out.Artifact = in.Artifact
	out.UnifiedMemoryRequest = in.UnifiedMemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedModel.
func (in *ResolvedModel) DeepCopy() *ResolvedModel {
	if in == nil {
		return nil
	}
	out := new(ResolvedModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedShell) DeepCopyInto(out *ResolvedShell) {
	*out = *in
	out.UnifiedMemoryRequest = in.UnifiedMemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedShell.
func (in *ResolvedShell) DeepCopy() *ResolvedShell {
	if in == nil {
		return nil
	}
	out := new(ResolvedShell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignaturePolicy) DeepCopyInto(out *SignaturePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignaturePolicy.
func (in *SignaturePolicy) DeepCopy() *SignaturePolicy {
	if in == nil {
		return nil
	}
	out := new(SignaturePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopAcknowledgement) DeepCopyInto(out *StopAcknowledgement) {
	*out = *in
	in.StoppedAt.DeepCopyInto(&out.StoppedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopAcknowledgement.
func (in *StopAcknowledgement) DeepCopy() *StopAcknowledgement {
	if in == nil {
		return nil
	}
	out := new(StopAcknowledgement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadModelReference) DeepCopyInto(out *WorkloadModelReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadModelReference.
func (in *WorkloadModelReference) DeepCopy() *WorkloadModelReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadModelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadObjectReference) DeepCopyInto(out *WorkloadObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadObjectReference.
func (in *WorkloadObjectReference) DeepCopy() *WorkloadObjectReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResources) DeepCopyInto(out *WorkloadResources) {
	*out = *in
	out.UnifiedMemoryRequest = in.UnifiedMemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResources.
func (in *WorkloadResources) DeepCopy() *WorkloadResources {
	if in == nil {
		return nil
	}
	out := new(WorkloadResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSchedulingIntent) DeepCopyInto(out *WorkloadSchedulingIntent) {
	*out = *in
	out.HostRef = in.HostRef
	if in.ModelRef != nil {
		in, out := &in.ModelRef, &out.ModelRef
		*out = new(ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSchedulingIntent.
func (in *WorkloadSchedulingIntent) DeepCopy() *WorkloadSchedulingIntent {
	if in == nil {
		return nil
	}
	out := new(WorkloadSchedulingIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadShell) DeepCopyInto(out *WorkloadShell) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadShell.
func (in *WorkloadShell) DeepCopy() *WorkloadShell {
	if in == nil {
		return nil
	}
	out := new(WorkloadShell)
	in.DeepCopyInto(out)
	return out
}
